"""Template-based plain-English contract summarizer. Zero LLM."""
from __future__ import annotations

from clauselens.rulebook.schema import RiskFlag
from clauselens.utils.logger import get_logger

log = get_logger(__name__)

CONTRACT_TYPE_LABELS = {
    "rental": "residential lease agreement",
    "employment": "employment contract",
    "freelance": "freelance / contractor agreement",
    "saas": "SaaS service agreement",
    "loan": "loan agreement",
    "unknown": "contract",
}


def _format_money(amount: float | None) -> str:
    if amount is None:
        return "an unspecified amount"
    return f"${amount:,.0f}" if amount >= 1 else f"${amount:.2f}"


def summarize(contract_type: str,
              terms: dict,
              flags: list[RiskFlag],
              health: dict) -> str:
    """Generate a plain-English paragraph summary."""
    label = CONTRACT_TYPE_LABELS.get(contract_type, "contract")

    # Opening
    parts = [f"This is a **{label}**."]

    # Money mention
    if terms.get("max_money"):
        parts.append(f"The largest monetary value mentioned is **{_format_money(terms['max_money'])}**.")

    # Duration mention
    if terms.get("max_duration_days"):
        days = terms["max_duration_days"]
        if days >= 365:
            parts.append(f"The longest duration referenced is **{days // 365} year(s)**.")
        elif days >= 30:
            parts.append(f"The longest duration referenced is **~{days // 30} month(s)**.")

    # Percentages
    if terms.get("max_percentage"):
        parts.append(f"The highest percentage mentioned is **{terms['max_percentage']}%**.")

    # Risk summary
    high = health["high_flags"]
    med = health["medium_flags"]
    low = health["low_flags"]
    parts.append(
        f"\n\nOur scan identified **{high} high-severity**, **{med} medium**, "
        f"and **{low} low-severity** concerns. "
        f"Overall Contract Health Score: **{health['score']}/100 (Grade {health['grade']} — {health['label']})**."
    )

    # Top flag callouts
    if flags:
        high_flags = [f for f in flags if f.severity == "HIGH"][:3]
        if high_flags:
            parts.append("\n\n**Top concerns to review before signing:**")
            for f in high_flags:
                parts.append(f"- 🔴 **{f.name}** — {f.plain_english}")

    # Disclaimer
    parts.append(
        "\n\n*This summary is generated by automated rule-based analysis and is not "
        "legal advice. Consult a licensed attorney before signing any contract with "
        "significant legal or financial consequences.*"
    )

    summary = " ".join(parts)
    log.info(f"Summary generated: {len(summary)} chars")
    return summary